set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Enable focus events for vim autoread
set -g focus-events on
# Fix Vim ESC delay
set -sg escape-time 0

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Use Alt-arrow keys without prefix key to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window


set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'


set -ga terminal-overrides ',xterm-256color:Tc'
# Add '-xterm' to the back of the name for xterm256 compatibility
# E.g. 'dark-medium-xterm'
set -g @plugin 'tmux-plugins/tmux-yank'


run '~/.tmux/plugins/tpm/tpm'

# set vi-mode
set-window-option -g mode-keys vi
# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"


# ============================================
# APPEARANCE
# ============================================
#
# moonfly theme for tmux
#
# Upstream: github.com/bluz71/vim-moonfly-colors

# Set status line, windows, pane and message colors.
set -g message-style "bg=#1c1c1c,fg=#9c9c9c"
set -g pane-active-border-style "bg=#080808,fg=#80a0ff"
set -g pane-border-style "bg=#080808,fg=#303030"
set -g status-style "bg=#1c1c1c,fg=#9c9c9c"
setw -g window-status-activity-style none
setw -g window-status-current-style "bg=#353946,fg=#80a0ff"
# Set active and inactive window style.
setw -g window-status-current-format " #I #[fg=#9c9c9c] #[fg=default]#W #[fg=#e65e72]#{?window_flags,#{window_flags}, }#[fg=default] "
setw -g window-status-format " #I  #W #[fg=#e65e72]#{?window_flags,#{window_flags}, }#[fg=default] "

# Set status bar components and style.
set -g status-left "#[fg=#f09479]⠶ #[fg=#80a0ff]#S@#h "
set -g status-right "%H:%M"
if-shell '[[ $(uname) = Darwin ]]' \
    'set -g status-right "%a %d %b  #[fg=#80a0ff]%I:%M%p"' \
    'set -g status-right "%a %d %b  #[fg=#80a0ff]%I:%M%P"'
