[env]
TERM = "xterm-256color"

[window]
decorations = "Full"
opacity = 1.0
dynamic_padding = true

[font]
normal = { family = "JetBrainsMono NF", style = "Regular"}
bold = { family = "JetBrainsMono NF", style = "Bold"}
italic = { family = "JetBrainsMono NF", style = "Italic"}
bold_italic = { family = "JetBrainsMono NF", style = "Bold Italic"}
size = 14
builtin_box_drawing = true

[cursor]
style = { shape = "Underline", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "Off" }

[scrolling]
history = 100000

[mouse]
hide_when_typing = true

[general]
import = [
  "~/.config/alacritty/themes/everforest_dark.toml"
]
