return {
  ensure_installed = {
    "black",
    "clangd",
    "clang-format",
    "gofumpt",
    "goimports",
    "golines",
    "gopls",
    "lua-language-server",
    "pyright",
    "rust-analyzer",
    "rustfmt",
    "stylua",
    "ruff",
    "shfmt",
    "htmx-lsp",
    "prettier",
  },
}
